RandomSeed: 10

Arch:
  input_dim: 1
  num_classes: 4

Augment: strong

Data:
  labeled_data_ratio: 0.05
  unlabeled_data_ratio: 0.95

ContrastData:
  group_sample_num: 8
  partition_sample_num: 1
  num_workers: 6
  shuffle: false

LabeledData:
  shuffle: true
  batch_size: 16
  num_workers: 8

Trainer:
  name: contrast
  save_dir: test_semi_trainer
  device: cuda
  num_batches: 500
  max_epoch_train_decoder: 50
  max_epoch_train_encoder: 100
  max_epoch_train_finetune: 80
  train_encoder: True
  train_decoder: True

PretrainEncoder:
  group_option: partition
  lr: 0.000001
  weight_decay: 0.00001
  multiplier: 300
  warmup_max: 10
  extract_position: Conv5
  ptype: mlp

PretrainDecoder:
  lr: 0.000001
  weight_decay: 0.0
  multiplier: 300
  warmup_max: 10
  enable_grad_from: Conv1
  extract_position: Up_conv3
  ptype: mlp


FineTune:
  lr: 0.0000001
  weight_decay: 0.00001
  multiplier: 400
  warmup_max: 10



#Checkpoint: runs/test_pipeline